### ISSUE TITLE
2nd check of QC_plus

### ISSUE THREAD

**Issue by mairi-mcclean** [Talavera-Lopez-Lab/TB_cellular_circuits#4]
@cartal notebook amended with shiny new UMAP panels

**Comment by cartal** [comment]
@mairi-mcclean please add a link to the notebook so I can see it :)

**Comment by mairi-mcclean** [comment]
https://github.com/Talavera-Lopez-Lab/TB_cellular_circuits/blob/qc_plus/1-sample_QC/221201_QCplus_CaiY2022_MM.ipynb

**Comment by cartal** [comment]
I added a couple of comments, please check [here](https://app.reviewnb.com/Talavera-Lopez-Lab/TB_cellular_circuits/blob/qc_plus/1-sample_QC%2F221201_QCplus_CaiY2022_MM.ipynb).
